### ISSUE TITLE
latest source?

### ISSUE THREAD

**Issue by hotzeplotz** [bear/indie-stats#5]
@bear, is the published bear/indie-stats the latest version of the code available? the live site at https://indie-stats.com/ seems to have features/templates/scripts that are not in the public repo. i'm working on documentation/visualizations/etc. and would like to base my patches on the latest upstream code.

**Comment by bear** [comment]
I will check tonight and make sure.

I just added you as a collaborator - so please do make any changes you find improve things. I will also automate the deploy later.

**Comment by bear** [comment]
also, many apologies for not seeing this issue for so long!

**Comment by bear** [comment]
the repo is now current
